services:
  - type: web
    name: upbit-krw-bot
    env: node
    plan: free
    buildCommand: bash build.sh
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
